use crate::new_br;
use classfile::BytesRef;
use std::sync::OnceLock;

pub static S_INIT: OnceLock<BytesRef> = OnceLock::new();
pub static S_CLINIT: OnceLock<BytesRef> = OnceLock::new();
pub static S_CLINIT_SIG: OnceLock<BytesRef> = OnceLock::new();
pub static S_RUN_SIG: OnceLock<BytesRef> = OnceLock::new();
pub static S_NEW_STRING_SIG: OnceLock<BytesRef> = OnceLock::new();
pub static S_CLAZZ: OnceLock<BytesRef> = OnceLock::new();
pub static S_FD: OnceLock<BytesRef> = OnceLock::new();
pub static S_I: OnceLock<BytesRef> = OnceLock::new();
pub static S_SLOT: OnceLock<BytesRef> = OnceLock::new();
pub static S_MODIFIERS: OnceLock<BytesRef> = OnceLock::new();
pub static S_NAME: OnceLock<BytesRef> = OnceLock::new();
pub static S_SIGNATURE: OnceLock<BytesRef> = OnceLock::new();
pub static S_CONSTANT_POOL_OOP: OnceLock<BytesRef> = OnceLock::new();
pub static S_RUN: OnceLock<BytesRef> = OnceLock::new();
pub static S_ERR: OnceLock<BytesRef> = OnceLock::new();
pub static S_OUT: OnceLock<BytesRef> = OnceLock::new();
pub static S_IN: OnceLock<BytesRef> = OnceLock::new();
pub static S_JAVA_LANG_CLASS: OnceLock<BytesRef> = OnceLock::new();
pub static S_JAVA_LANG_OBJECT: OnceLock<BytesRef> = OnceLock::new();
pub static S_JAVA_LANG_STRING: OnceLock<BytesRef> = OnceLock::new();
pub static S_JAVA_IO_FD: OnceLock<BytesRef> = OnceLock::new();
pub static S_JAVA_IO_PRINT_STREAM: OnceLock<BytesRef> = OnceLock::new();
pub static S_JAVA_IO_INPUT_STREAM: OnceLock<BytesRef> = OnceLock::new();

pub fn init() {
    S_INIT.get_or_init(|| new_br("<init>"));
    S_CLINIT.get_or_init(|| new_br("<clinit>"));
    S_CLINIT_SIG.get_or_init(|| new_br("()V"));
    S_RUN_SIG.get_or_init(|| new_br("()Ljava/lang/Object;"));
    S_NEW_STRING_SIG.get_or_init(|| new_br("([C)V"));
    S_CLAZZ.get_or_init(|| new_br("clazz"));
    S_FD.get_or_init(|| new_br("fd"));
    S_I.get_or_init(|| new_br("I"));
    S_SLOT.get_or_init(|| new_br("slot"));
    S_MODIFIERS.get_or_init(|| new_br("modifiers"));
    S_NAME.get_or_init(|| new_br("name"));
    S_SIGNATURE.get_or_init(|| new_br("signature"));
    S_CONSTANT_POOL_OOP.get_or_init(|| new_br("constantPoolOop"));
    S_RUN.get_or_init(|| new_br("run"));
    S_ERR.get_or_init(|| new_br("err"));
    S_OUT.get_or_init(|| new_br("out"));
    S_IN.get_or_init(|| new_br("in"));
    S_JAVA_LANG_CLASS.get_or_init(|| new_br("Ljava/lang/Class;"));
    S_JAVA_LANG_OBJECT.get_or_init(|| new_br("Ljava/lang/Object;"));
    S_JAVA_LANG_STRING.get_or_init(|| new_br("Ljava/lang/String;"));
    S_JAVA_IO_FD.get_or_init(|| new_br("Ljava/io/FileDescriptor;"));
    S_JAVA_IO_PRINT_STREAM.get_or_init(|| new_br("Ljava/io/PrintStream;"));
    S_JAVA_IO_INPUT_STREAM.get_or_init(|| new_br("Ljava/io/InputStream;"));
}
